version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - ${APP_NETWORK_NAME}
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
      - ./internal/adapter/driven/db/migration/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql into the container

  app-service:
    image: ${APP_IMAGE}  # Specify the image name and tag
    container_name: ${CONTAINER_NAME} 
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${APP_PORT}
      IP: ${APP_IP}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    restart: always
    networks:
      - ${APP_NETWORK_NAME}

networks:
  APP_NETWORK:
    driver: bridge
    external: true

volumes:
  postgres-user-data:
